// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiHOT65PJ--bz6xt1mlm_2wjQd-H3ZwQ',
    appId: '1:406249002789:android:d97b86bd20b78c91202ccc',
    messagingSenderId: '406249002789',
    projectId: 'fir-tutorial-d4b6f',
    storageBucket: 'fir-tutorial-d4b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlwrJldQT3O1yaa62IgPkNi3k0vhqPRM',
    appId: '1:406249002789:ios:87ee97c9cbd58239202ccc',
    messagingSenderId: '406249002789',
    projectId: 'fir-tutorial-d4b6f',
    storageBucket: 'fir-tutorial-d4b6f.appspot.com',
    androidClientId: '406249002789-3uii55bcs7mm7pqhsqg4our307p9rudp.apps.googleusercontent.com',
    iosClientId: '406249002789-8qcta5ftmatf5s0qli1jp7u5v6et6fjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBasic',
  );
}
