// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIb1-LfaC-YxqHESdnEnPr2C6YLW5IRMA',
    appId: '1:406249002789:web:5e4083eef1eed4ef202ccc',
    messagingSenderId: '406249002789',
    projectId: 'fir-tutorial-d4b6f',
    authDomain: 'fir-tutorial-d4b6f.firebaseapp.com',
    storageBucket: 'fir-tutorial-d4b6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiHOT65PJ--bz6xt1mlm_2wjQd-H3ZwQ',
    appId: '1:406249002789:android:d97b86bd20b78c91202ccc',
    messagingSenderId: '406249002789',
    projectId: 'fir-tutorial-d4b6f',
    storageBucket: 'fir-tutorial-d4b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlwrJldQT3O1yaa62IgPkNi3k0vhqPRM',
    appId: '1:406249002789:ios:87ee97c9cbd58239202ccc',
    messagingSenderId: '406249002789',
    projectId: 'fir-tutorial-d4b6f',
    storageBucket: 'fir-tutorial-d4b6f.appspot.com',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLlwrJldQT3O1yaa62IgPkNi3k0vhqPRM',
    appId: '1:406249002789:ios:87ee97c9cbd58239202ccc',
    messagingSenderId: '406249002789',
    projectId: 'fir-tutorial-d4b6f',
    storageBucket: 'fir-tutorial-d4b6f.appspot.com',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIb1-LfaC-YxqHESdnEnPr2C6YLW5IRMA',
    appId: '1:406249002789:web:93f200fa25eb0843202ccc',
    messagingSenderId: '406249002789',
    projectId: 'fir-tutorial-d4b6f',
    authDomain: 'fir-tutorial-d4b6f.firebaseapp.com',
    storageBucket: 'fir-tutorial-d4b6f.appspot.com',
  );
}
